# Generated by Django 4.0.4 on 2022-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, null=True)),
                ('type_of_scenario', models.CharField(max_length=200, null=True)),
                ('action', models.TextField(null=True)),
                ('list_element', models.TextField(null=True)),
                ('input_element', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=200, null=True)),
                ('feature', models.CharField(max_length=200, null=True)),
                ('feature_description', models.CharField(max_length=200, null=True)),
                ('pre_condition', models.CharField(max_length=200, null=True)),
                ('post_condition', models.CharField(max_length=200, null=True)),
                ('sum_element', models.TextField(null=True)),
            ],
        ),
    ]
