# Generated by Django 4.0.4 on 2022-05-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_ucs_usecasescenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='use_case_scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.usecasescenario'),
        ),
    ]
