# Generated by Django 4.0.4 on 2022-05-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_sum_element_usecasescenario_alternative_sorted_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasescenario',
            name='salt',
            field=models.TextField(null=True),
        ),
    ]
