# Generated by Django 4.0.4 on 2022-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_usecasescenario_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecasescenario',
            old_name='alternative_sorted_element',
            new_name='alternative_element',
        ),
        migrations.RenameField(
            model_name='usecasescenario',
            old_name='exception_sorted_element',
            new_name='alternative_salt',
        ),
        migrations.RenameField(
            model_name='usecasescenario',
            old_name='elements',
            new_name='exception_element',
        ),
        migrations.RenameField(
            model_name='usecasescenario',
            old_name='normal_sorted_element',
            new_name='exception_salt',
        ),
        migrations.AddField(
            model_name='usecasescenario',
            name='normal_element',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usecasescenario',
            name='normal_salt',
            field=models.TextField(null=True),
        ),
    ]
