# Generated by Django 4.0.4 on 2022-05-29 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_remove_usecasescenario_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasescenario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecasescenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
