# Generated by Django 4.0.4 on 2022-05-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_usecasescenario_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecasescenario',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usecasescenario',
            name='updated_at',
        ),
    ]
