# Generated by Django 4.0.4 on 2022-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_action_created_by_usecasescenario_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasescenario',
            name='system',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
